import json
import os
import requests
import sys
from pathlib import Path
from dotenv import load_dotenv

# Path patching for standalone run
BASE_DIR = Path(__file__).parent.parent.parent.absolute()
sys.path.append(str(BASE_DIR))
sys.path.append(str(BASE_DIR / "backend" / "core"))
from backend.core.schemas import StudyPlan
from backend.core.adaptive_prompts import get_generator_instructions

load_dotenv()

HTML_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Teacher Teaching Plan</title>
    <style>
        body { font-family: 'Helvetica', 'Arial', sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 20px; }
        .header { text-align: center; border-bottom: 2px solid #2c3e50; padding-bottom: 20px; margin-bottom: 30px; }
        h1 { color: #2c3e50; margin: 0; font-size: 28px; }
        h2 { color: #7f8c8d; margin: 5px 0 0 0; font-size: 18px; font-weight: normal; }
        .section { margin-bottom: 30px; background: #fff; padding: 20px; border-radius: 8px; box-shadow: 0 2px 5px rgba(0,0,0,0.05); border-left: 5px solid #3498db; }
        .section-title { font-size: 20px; font-weight: bold; color: #2980b9; margin-bottom: 15px; border-bottom: 1px solid #eee; padding-bottom: 10px; }
        .content { font-size: 14px; }
        ul { margin-top: 5px; padding-left: 20px; }
        li { margin-bottom: 5px; }
        .highlight { background-color: #f8f9fa; padding: 15px; border-radius: 5px; border: 1px solid #e9ecef; }
        .checklist { list-style-type: none; padding: 0; }
        .checklist li:before { content: ""; margin-right: 10px; font-weight: bold; }
        .raw-example { background-color: #fff3cd; border-left: 5px solid #ffc107; padding: 10px; margin-bottom: 10px; font-style: italic; }
        .meta { font-size: 12px; color: #999; text-align: right; margin-top: 50px; border-top: 1px solid #eee; padding-top: 10px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Teacher Teaching Plan</h1>
        <h2>Topic: {{topic_name}}</h2>
    </div>

    <!-- 1. Overview -->
    <div class="section">
        <div class="section-title">1. Topic Overview</div>
        <div class="content">{{overview}}</div>
    </div>

    <!-- 2. Learning Objectives -->
    <div class="section">
        <div class="section-title">2. Learning Objectives</div>
        <div class="content">
            <ul>
                {{objectives}}
            </ul>
        </div>
    </div>
    
    <!-- NEW: Textbook Examples (Zero Hallucination) -->
    <div class="section">
        <div class="section-title">3. Textbook Examples (Direct Extraction)</div>
        <div class="content">
            {{raw_examples}}
        </div>
    </div>

    <!-- 4. Prerequisites -->
    <div class="section">
        <div class="section-title">4. Prerequisites</div>
        <div class="content">{{prerequisites}}</div>
    </div>

    <!-- 5. Teaching Plan -->
    <div class="section">
        <div class="section-title">5. Teaching Plan (Step-by-Step)</div>
        <div class="content">{{teaching_plan}}</div>
    </div>

    <!-- 6. Explanation -->
    <div class="section">
        <div class="section-title">6. Explanation (Level-Aware)</div>
        <div class="content">{{explanation}}</div>
    </div>

    <!-- 7. Worked Examples (AI Generated) -->
    <div class="section">
        <div class="section-title">7. Additional Worked Examples</div>
        <div class="content highlight">{{worked_examples}}</div>
    </div>

    <!-- 8. Classroom Questions -->
    <div class="section">
        <div class="section-title">8. Classroom Questions</div>
        <div class="content">
            <ul>
                {{questions}}
            </ul>
        </div>
    </div>

    <!-- 9. Homework -->
    <div class="section">
        <div class="section-title">9. Homework / Practice</div>
        <div class="content">{{homework}}</div>
    </div>

    <!-- 10. Assessment -->
    <div class="section">
        <div class="section-title">10. Assessment Checklist</div>
        <div class="content">
            <ul class="checklist">
                {{assessment}}
            </ul>
        </div>
    </div>

    <div class="meta">
        Generated by AI Teaching Assistant &bull; Source: {{source_meta}}
    </div>
</body>
</html>
"""

def generate_content(json_data, topic_index=0, difficulty="Beginner"):
    """Generate teaching plan content using LLM"""
    print(f"Generating content with LLM for level: {difficulty}")
    
    topic = json_data[topic_index]
    topic_name = topic['topic_name']
    objectives = "\n".join([f"- {obj}" for obj in topic['learning_objectives']])
    content_text = "\n".join([b['text'] for b in topic['content_blocks']])
    
    level_guidance = get_generator_instructions(difficulty, "plan")
    
    prompt = f"""
    You are an expert teacher. Create a detailed, level-aware teaching plan for the topic: "{topic_name}".
    
    TARGET STUDENT LEVEL: {difficulty}
    
    SOURCE DATA:
    Objectives: {objectives}
    Content Context: {content_text[:2000]}...
    
    PEDAGOGICAL INSTRUCTIONS FOR THIS TIER:
    {level_guidance}
    
    Return a JSON object with EXACTLY these fields (content should be HTML-safe text, use <br> for newlines):
    {{
        "overview": "Brief summary of what this topic covers (2-3 sentences) suitable for {difficulty} level",
        "prerequisites": "What students need to know before this lesson",
        "teaching_plan": "Step-by-step class lesson plan timeline matching the level instructions (Example: <b>5 mins:</b> Intro... <br> <b>15 mins:</b> Activity...)",
        "explanation": "Clear explanation of the core concept designed strictly for a student at {difficulty} level",
        "worked_examples": "2 clear examples with solutions matching the difficulty of the level",
        "questions": ["Question 1", "Question 2", "Question 3"], // JSON array of 3 to 5 thought-provoking questions, without <li> tags
        "homework": "3 short practice problems matching the difficulty of the level",
        "assessment": ["Check 1", "Check 2", "Check 3", "Check 4"] // JSON array of 4 to 6 checkpoint items to assess understanding, without <li> tags
    }}
    """
    
    api_key = os.getenv("GROQ_API_KEY")
    if not api_key:
        raise RuntimeError("GROQ_API_KEY not found in .env file")
        
    import instructor
    from groq import Groq
    client = instructor.from_groq(Groq(api_key=api_key))
    
    print("Generating study plan with Groq and Instructor...")
    try:
        plan = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            response_model=StudyPlan,
            messages=[
                {"role": "system", "content": "You are a helpful teaching assistant."},
                {"role": "user", "content": prompt}
            ],
            temperature=0.7,
            max_retries=2
        )
        return plan.model_dump()
    except Exception as e:
        print(f"Instructor Generation/Validation Failed: {e}")
        raise RuntimeError(f"Failed to generate study plan: {e}")

def create_html(json_data, llm_content, topic_index=0, source_meta="General Curriculum"):
    """Fill HTML template"""
    print(" Creating HTML...")
    
    topic = json_data[topic_index]
    
    # 1. Extract RAW EXAMPLES from JSON (Zero Hallucination)
    raw_examples = []
    for block in topic.get('content_blocks', []):
        if block.get('type') == 'example':
            text = block.get('text', '')
            if text:
                raw_examples.append(f'<div class="raw-example">Note from Textbook: {text}</div>')
    
    # Use only top 3 to save space
    raw_examples_html = "\n".join(raw_examples[:3]) if raw_examples else "<em>No specific examples extracted from text.</em>"
    
    # Format objectives list elements
    objs_html = "\n".join([f"<li>{obj}</li>" for obj in topic['learning_objectives']])
    
    # helper to ensure string
    def clean(val):
        if isinstance(val, list):
            return "<br>".join([str(item) for item in val])
        return str(val)

    html = HTML_TEMPLATE.replace("{{topic_name}}", str(topic['topic_name']))
    html = html.replace("{{source_meta}}", source_meta)
    html = html.replace("{{overview}}", clean(llm_content.get('overview', '')))
    html = html.replace("{{objectives}}", objs_html)
    
    # INSERT RAW EXAMPLES
    html = html.replace("{{raw_examples}}", raw_examples_html)
    
    html = html.replace("{{prerequisites}}", clean(llm_content.get('prerequisites', '')))
    html = html.replace("{{teaching_plan}}", clean(llm_content.get('teaching_plan', '')))
    html = html.replace("{{explanation}}", clean(llm_content.get('explanation', '')))
    html = html.replace("{{worked_examples}}", clean(llm_content.get('worked_examples', '')))
    
    # Questions might be a list or string with <li>
    questions = llm_content.get('questions', '')
    if isinstance(questions, list):
        questions = "\n".join([f"<li>{q}</li>" for q in questions])
    html = html.replace("{{questions}}", str(questions))
    
    html = html.replace("{{homework}}", clean(llm_content.get('homework', '')))
    
    # Assessment might be a list or string with <li>
    assessment = llm_content.get('assessment', '')
    if isinstance(assessment, list):
        assessment = "\n".join([f"<li>{a}</li>" for a in assessment])
    html = html.replace("{{assessment}}", str(assessment))
    
    return html

def convert_to_pdf(html_content, output_path="teaching_plan.pdf"):
    """Convert HTML to PDF using PDFShift API"""
    
    # Check environment variable for API Key
    api_key = os.getenv("PDFSHIFT_API_KEY") 
    
    if not api_key:
        print("PDFSHIFT_API_KEY not found. Saving as HTML instead.")
        html_path = output_path.replace(".pdf", ".html")
        with open(html_path, "w", encoding="utf-8") as f:
            f.write(html_content)
        print(f"Saved to {html_path}")
        return html_path

    print(" Converting to PDF via PDFShift...")
    response = requests.post(
        "https://api.pdfshift.io/v3/convert/pdf",
        auth=("api", api_key),
        json={
            "source": html_content,
            "landscape": False,
            "use_print": False
        }
    )

    if response.status_code == 200:
        with open(output_path, "wb") as f:
            f.write(response.content)
        print(f" Success! Saved to {output_path}")
        return output_path
    else:
        print(f"PDF Generation Failed: {response.text}")
        # Fallback to HTML
        with open("teaching_plan.html", "w", encoding="utf-8") as f:
            f.write(html_content)
        print("Saved HTML backup to teaching_plan.html")

def run_teaching_plan_generator(json_path, output_path, topic_index=0, difficulty="Beginner"):
    print("="*60)
    print(" Teacher Teaching Plan Generator")
    print("="*60)
    
    # 1. Load Data
    print(f" Loading {json_path}...")
    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
        
    # Check if data is list or dict
    if isinstance(data, dict):
        # normalize to list if single object
        data = [data]
        
    # 2. Generate Content with Active Prevention Loop
    from backend.verifier import ContentVerifier
    verifier = ContentVerifier()
    source_context = "\n".join([b['text'] for b in data[topic_index]['content_blocks']])
    
    max_retries = 3
    content = None
    
    for attempt in range(max_retries):
        print(f"\n--- Generation Attempt {attempt + 1}/{max_retries} ---")
        content = generate_content(data, topic_index, difficulty)
        
        # VERIFY (The Bias/Truth Layer)
        verification_result = verifier.verify(source_context, content, "Teaching Plan")
        
        # If score is good and no hallucination/bias, break out of the loop!
        if verification_result.get('score', 0) >= 85 and not verification_result.get('hallucination_found') and not verification_result.get('bias_found'):
            print("[SUCCESS] Content passed strict verification!")
            break
        else:
            print("[FAILED] Verification failed (Hallucination/Bias or Low Score). Retrying generation to prevent bad content...")
            if attempt == max_retries - 1:
                print("[WARNING] Max retries reached. Proceeding with best attempt (still flagged).")
                
    content['verification_status'] = verification_result

    # Extract dynamic grade and subject from path
    grade_str = "7"
    subject_str = "General"
    path_parts = Path(json_path).parts
    for part in path_parts:
        if "grade" in part.lower():
            grade_str = part.replace("Grade_", "").replace("grade_", "")
        elif part.lower() in ["mathematics", "physics", "chemistry", "biology", "science", "english", "history"]:
            subject_str = part
    
    source_meta = f"Grade {grade_str} {subject_str} Curriculum"

    # 3. Create HTML
    html = create_html(data, content, topic_index, source_meta)
    
    # 4. Generate PDF
    # Capture the ACTUAL output path (could be .html fallback)
    final_path = convert_to_pdf(html, output_path)
    return final_path

if __name__ == "__main__":
    # CLI usage: python generate_plan.py <path_to_json> [output_pdf_name]
    if len(sys.argv) < 2:
        print("Usage: python generate_plan.py <path_to_json> [output_pdf_name]")
        print("Example: python generate_plan.py generated_contents/user1/content/Grade_7/Math/json_output/chapter1.json plan.pdf")
        sys.exit(1)

    json_path = sys.argv[1]
    output_name = sys.argv[2] if len(sys.argv) > 2 else "teaching_plan.pdf"

    if os.path.exists(json_path):
        run_teaching_plan_generator(json_path, output_name)
    else:
        print(f"File not found: {json_path}")
